2020-03-27T00:28:14.150719+00:00 app[web.1]: 353
2020-03-27T00:28:14.150958+00:00 app[web.1]: 359
2020-03-27T00:28:14.151264+00:00 app[web.1]: 367
2020-03-27T00:28:14.151550+00:00 app[web.1]: 373
2020-03-27T00:28:14.151786+00:00 app[web.1]: 379
2020-03-27T00:28:14.151872+00:00 app[web.1]: 383
2020-03-27T00:28:14.152017+00:00 app[web.1]: 389
2020-03-27T00:28:14.152201+00:00 app[web.1]: 397
2020-03-27T00:28:14.152314+00:00 app[web.1]: 401
2020-03-27T00:28:14.152703+00:00 app[web.1]: 409
2020-03-27T00:28:14.153206+00:00 app[web.1]: 419
2020-03-27T00:28:14.153317+00:00 app[web.1]: 421
2020-03-27T00:28:14.153829+00:00 app[web.1]: 431
2020-03-27T00:28:14.153966+00:00 app[web.1]: 433
2020-03-27T00:28:14.154263+00:00 app[web.1]: 439
2020-03-27T00:28:14.154462+00:00 app[web.1]: 443
2020-03-27T00:28:14.154793+00:00 app[web.1]: 449
2020-03-27T00:28:14.155184+00:00 app[web.1]: 457
2020-03-27T00:28:14.155399+00:00 app[web.1]: 461
2020-03-27T00:28:14.155522+00:00 app[web.1]: 463
2020-03-27T00:28:14.155743+00:00 app[web.1]: 467
2020-03-27T00:28:14.156456+00:00 app[web.1]: 479
2020-03-27T00:28:14.156891+00:00 app[web.1]: 487
2020-03-27T00:28:14.157153+00:00 app[web.1]: 491
2020-03-27T00:28:14.157617+00:00 app[web.1]: 499
2020-03-27T00:28:14.157958+00:00 app[web.1]: 503
2020-03-27T00:28:14.158294+00:00 app[web.1]: 509
2020-03-27T00:28:14.159025+00:00 app[web.1]: 521
2020-03-27T00:28:14.159098+00:00 app[web.1]: 523
2020-03-27T00:28:14.159820+00:00 app[web.1]: 541
2020-03-27T00:28:14.161722+00:00 app[web.1]: [2020-03-27 00:28:14,160] ERROR in app: Exception on / [GET]
2020-03-27T00:28:14.161724+00:00 app[web.1]: Traceback (most recent call last):
2020-03-27T00:28:14.161725+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
2020-03-27T00:28:14.161726+00:00 app[web.1]: response = self.full_dispatch_request()
2020-03-27T00:28:14.161727+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
2020-03-27T00:28:14.161727+00:00 app[web.1]: return self.finalize_request(rv)
2020-03-27T00:28:14.161728+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1630, in finalize_request
2020-03-27T00:28:14.161728+00:00 app[web.1]: response = self.make_response(rv)
2020-03-27T00:28:14.161729+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1725, in make_response
2020-03-27T00:28:14.161729+00:00 app[web.1]: raise ValueError('View function did not return a response')
2020-03-27T00:28:14.161729+00:00 app[web.1]: ValueError: View function did not return a response
2020-03-27T00:28:14.162151+00:00 app[web.1]: 10.5.241.183 - - [27/Mar/2020 00:28:14] "GET / HTTP/1.1" 500 -
2020-03-27T00:28:14.163374+00:00 heroku[router]: at=info method=GET path="/" host=powerful-chamber-79776.herokuapp.com request_id=68694752-ab85-4389-ab1e-7039b761a42c fwd="179.100.13.187" dyno=web.1 connect=1ms service=20ms status=500 bytes=450 protocol=https
2020-03-27T00:28:14.983651+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=powerful-chamber-79776.herokuapp.com request_id=dc15b8b3-7223-4ed7-b260-d052b05a04ea fwd="179.100.13.187" dyno=web.1 connect=1ms service=11ms status=404 bytes=380 protocol=https
2020-03-27T00:28:14.982367+00:00 app[web.1]: 10.61.189.68 - - [27/Mar/2020 00:28:14] "GET /favicon.ico HTTP/1.1" 404 -
2020-03-27T00:32:29.000000+00:00 app[api]: Build started by user mah-martins@live.com
2020-03-27T00:33:00.605669+00:00 heroku[web.1]: Restarting
2020-03-27T00:33:00.621214+00:00 heroku[web.1]: State changed from up to starting
2020-03-27T00:32:59.290499+00:00 app[api]: Release v4 created by user mah-martins@live.com
2020-03-27T00:33:02.125844+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-03-27T00:32:59.290499+00:00 app[api]: Deploy 06f35354 by user mah-martins@live.com
2020-03-27T00:33:02.202253+00:00 heroku[web.1]: Process exited with status 143
2020-03-27T00:33:04.529016+00:00 heroku[web.1]: Starting process with command `python primos.py`
2020-03-27T00:33:07.385501+00:00 app[web.1]: * Running on http://0.0.0.0:45796/ (Press CTRL+C to quit)
2020-03-27T00:33:07.000000+00:00 app[api]: Build succeeded
2020-03-27T00:33:08.953202+00:00 heroku[web.1]: State changed from starting to up
2020-03-27T00:33:21.464045+00:00 heroku[router]: at=info method=GET path="/" host=powerful-chamber-79776.herokuapp.com request_id=be236d88-31d8-4c7a-970b-910ced7460f7 fwd="179.100.13.187" dyno=web.1 connect=0ms service=14ms status=500 bytes=450 protocol=https
2020-03-27T00:33:21.464770+00:00 app[web.1]: [2020-03-27 00:33:21,462] ERROR in app: Exception on / [GET]
2020-03-27T00:33:21.464781+00:00 app[web.1]: Traceback (most recent call last):
2020-03-27T00:33:21.464783+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
2020-03-27T00:33:21.464783+00:00 app[web.1]: response = self.full_dispatch_request()
2020-03-27T00:33:21.464784+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
2020-03-27T00:33:21.464784+00:00 app[web.1]: return self.finalize_request(rv)
2020-03-27T00:33:21.464785+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1630, in finalize_request
2020-03-27T00:33:21.464785+00:00 app[web.1]: response = self.make_response(rv)
2020-03-27T00:33:21.464786+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1740, in make_response
2020-03-27T00:33:21.464786+00:00 app[web.1]: rv = self.response_class.force_type(rv, request.environ)
2020-03-27T00:33:21.464786+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/werkzeug/wrappers.py", line 921, in force_type
2020-03-27T00:33:21.464787+00:00 app[web.1]: response = BaseResponse(*_run_wsgi_app(response, environ))
2020-03-27T00:33:21.464787+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
2020-03-27T00:33:21.464788+00:00 app[web.1]: return _run_wsgi_app(*args)
2020-03-27T00:33:21.464788+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
2020-03-27T00:33:21.464789+00:00 app[web.1]: app_rv = app(environ, start_response)
2020-03-27T00:33:21.464789+00:00 app[web.1]: TypeError: 'int' object is not callable
2020-03-27T00:33:21.465226+00:00 app[web.1]: 10.33.187.161 - - [27/Mar/2020 00:33:21] "GET / HTTP/1.1" 500 -
2020-03-27T00:33:22.097871+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=powerful-chamber-79776.herokuapp.com request_id=6d8e3bc1-f270-4656-8afc-cb40969c6866 fwd="179.100.13.187" dyno=web.1 connect=1ms service=2ms status=404 bytes=380 protocol=https
2020-03-27T00:33:22.096394+00:00 app[web.1]: 10.11.150.203 - - [27/Mar/2020 00:33:22] "GET /favicon.ico HTTP/1.1" 404 -
2020-03-27T00:48:39.000000+00:00 app[api]: Build started by user mah-martins@live.com
2020-03-27T00:49:02.758353+00:00 heroku[web.1]: Restarting
2020-03-27T00:49:02.774656+00:00 heroku[web.1]: State changed from up to starting
2020-03-27T00:49:02.542032+00:00 app[api]: Release v5 created by user mah-martins@live.com
2020-03-27T00:49:02.542032+00:00 app[api]: Deploy e40931a7 by user mah-martins@live.com
2020-03-27T00:49:03.861210+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-03-27T00:49:03.981483+00:00 heroku[web.1]: Process exited with status 143
2020-03-27T00:49:05.916319+00:00 heroku[web.1]: Starting process with command `python primos.py`
2020-03-27T00:49:08.313303+00:00 app[web.1]: * Running on http://0.0.0.0:57830/ (Press CTRL+C to quit)
2020-03-27T00:49:08.728353+00:00 heroku[web.1]: State changed from starting to up
2020-03-27T00:49:11.000000+00:00 app[api]: Build succeeded
2020-03-27T00:49:23.983632+00:00 heroku[router]: at=info method=GET path="/" host=powerful-chamber-79776.herokuapp.com request_id=1c804df9-1985-4f2c-b232-8613c826ba03 fwd="179.100.13.187" dyno=web.1 connect=0ms service=11ms status=200 bytes=526 protocol=https
2020-03-27T00:49:23.986767+00:00 app[web.1]: 10.29.86.227 - - [27/Mar/2020 00:49:23] "GET / HTTP/1.1" 200 -
2020-03-27T01:24:29.623550+00:00 heroku[web.1]: Idling
2020-03-27T01:24:29.627129+00:00 heroku[web.1]: State changed from up to down
2020-03-27T01:24:30.695273+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-03-27T01:24:30.785889+00:00 heroku[web.1]: Process exited with status 143
2020-04-02T22:51:52.145544+00:00 heroku[web.1]: Unidling
2020-04-02T22:51:52.149111+00:00 heroku[web.1]: State changed from down to starting
2020-04-02T22:51:59.062836+00:00 app[web.1]: * Running on http://0.0.0.0:13092/ (Press CTRL+C to quit)
2020-04-02T22:52:00.123246+00:00 heroku[web.1]: State changed from starting to up
2020-04-02T22:52:01.217216+00:00 heroku[router]: at=info method=GET path="/" host=powerful-chamber-79776.herokuapp.com request_id=1c357007-2e82-4aab-89e2-225090860d66 fwd="177.76.146.107" dyno=web.1 connect=0ms service=15ms status=200 bytes=526 protocol=https
2020-04-02T22:52:01.214996+00:00 app[web.1]: 10.37.222.189 - - [02/Apr/2020 22:52:01] "GET / HTTP/1.1" 200 -
